### ISSUE TITLE
Missing iridia_af Module

### ISSUE THREAD

**Issue by Gooda97** [cedricgilon/iridia-af#1]
Firstly, thank you for your incredible work. The effort you've put into this is greatly appreciated.

I tried to run the script but the <code>iridia_af</code> module seems to be missing from the repository. I downloaded the data but I think I need the <code>hyperparameters</code> file and the <code>Record</code> file.

At least you may give a sample and a little explanation of these files structure.

**Comment by Gooda97** [comment]
I found them in the <code>dev</code> branch.

**Comment by cedricgilon** [comment]
The two files are also contained in the `main` branch, in the `iridia_af`module and in the `examples` module.
